### ISSUE TITLE
Can't save shots after disk full

### ISSUE THREAD

**Issue by ulope** [ebengoechea/de1app_plugin_SDB#2]
My tablet ran out of space (due to some excessive logging which I'm not quite sure the origin of). This seems to have caused some sort of file corruption.

But even after making space available I'm getting the following error after every action (shot, flush, steam, etc.):
```
can't read "file_props(clock)": no such element in array
can't read "file_props(clock)": no such element in array
    while executing
"set shot_data(clock) $file_props(clock)"
    (procedure "load_shot" line 18)
    invoked from within
"load_shot $::settings(espresso_clock)"
    (procedure "::plugins::SDB::save_espresso_to_history_hook" line 70)
    invoked from within
"::plugins::SDB::save_espresso_to_history_hook  [dict get $event_dict previous_state]  [dict get $event_dict this_state]  "
    (lambda term "event_dict {
			::plugins::SDB::save_espresso_to_history_hoo..." line 2)
    invoked from within
"::apply {event_dict {
			::plugins::SDB::save_espresso_to_history_hook  [dict get $event_dict previous_state]  [dict get $event_dict this_state]  }} {..."
    ("after" script)
```

The sqlite db appears to be fine (at least a `.dump` completed without errors).

**Comment by ebengoechea** [comment]
Hi, can you please run the Log Uploader extension and copy the link? If it doesn't work, just share the ``de1plus\log.txt`` on the tablet after closing the app. Maybe there I can see more info to diagnose the problem.

**Comment by ulope** [comment]
Sorry, forgot to follow up here. I restored from backup and after that the problem went away.

So I'm going to close this.
